# Generated by Django 3.1.2 on 2020-11-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('methodID', models.AutoField(primary_key=True, serialize=False)),
                ('input_file', models.JSONField()),
                ('output_file', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
