# Generated by Django 3.1.2 on 2020-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='method',
            name='input_file',
            field=models.FileField(upload_to='inputs'),
        ),
        migrations.AlterField(
            model_name='method',
            name='output_file',
            field=models.FileField(upload_to='outputs'),
        ),
    ]
