# Generated by Django 3.1.2 on 2020-11-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201128_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='input_file',
            field=models.FileField(upload_to='static/inputs'),
        ),
        migrations.AlterField(
            model_name='method',
            name='output_file',
            field=models.FileField(upload_to='static/outputs'),
        ),
    ]
