# Generated by Django 3.1.2 on 2020-11-29 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201129_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='input_file',
            field=models.FileField(upload_to='static/inputs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
