# Generated by Django 3.1.2 on 2020-12-01 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20201129_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='input_file',
            field=models.FileField(upload_to='static/inputs', verbose_name=django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])),
        ),
    ]
