# Generated by Django 3.1.2 on 2020-12-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201201_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='input_file',
            field=models.FileField(upload_to='static/inputs'),
        ),
    ]
